# Generated by Django 2.0.2 on 2018-07-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='user_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
