# Generated by Django 2.0.2 on 2018-07-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180721_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='user_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
