# Generated by Django 2.0.2 on 2018-07-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180721_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='user_image',
            field=models.ImageField(default='/media/images/default.png', upload_to='images/'),
        ),
    ]
