# Generated by Django 2.0.7 on 2018-07-21 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditdebit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rupees', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pub_datetime', models.DateTimeField()),
                ('credit_or_debit', models.CharField(choices=[('credit', 'CREDIT'), ('debit', 'DEBIT')], default='CREDIT', max_length=6)),
                ('used_for', models.CharField(choices=[('household', 'HOUSEHOLD'), ('personal', 'PERSONAL')], default='HOUSEHOLD', max_length=15)),
                ('money_source', models.CharField(choices=[('khata', 'KHATA'), ('own', 'OWN')], default='KHATA', max_length=15)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
