# Generated by Django 2.0.7 on 2018-07-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditdebit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditdebit',
            name='transaction_type',
            field=models.CharField(choices=[('inflow', 'INFLOW'), ('outflow', 'OUTFLOW')], default='OUTFLOW', max_length=15),
        ),
    ]
