# Generated by Django 2.0.7 on 2018-07-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditdebit', '0002_creditdebit_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditdebit',
            name='credit_or_debit',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='Credit', max_length=6),
        ),
        migrations.AlterField(
            model_name='creditdebit',
            name='money_source',
            field=models.CharField(choices=[('khata', 'Khata'), ('own', 'Own')], default='Khata', max_length=15),
        ),
        migrations.AlterField(
            model_name='creditdebit',
            name='transaction_type',
            field=models.CharField(choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], default='Outflow', max_length=15),
        ),
        migrations.AlterField(
            model_name='creditdebit',
            name='used_for',
            field=models.CharField(choices=[('household', 'Household'), ('personal', 'Personal')], default='Household', max_length=15),
        ),
    ]
