# Generated by Django 2.0.7 on 2018-07-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditdebit', '0005_auto_20180722_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditdebit',
            name='remaining_bal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
