# Generated by Django 2.0.7 on 2018-07-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditdebit', '0008_remove_creditdebit_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField()),
                ('username', models.TextField()),
                ('descript', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flag_on_off', models.BooleanField(default=1)),
                ('give_take', models.BooleanField(default=1)),
            ],
        ),
    ]
