# Generated by Django 2.0.7 on 2018-07-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditdebit', '0009_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditdebit',
            name='rupees',
            field=models.IntegerField(),
        ),
    ]
