# Generated by Django 2.0.7 on 2018-07-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditdebit', '0011_inv_equ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditdebit',
            name='remaining_bal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='inv_equ',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
